### PR TITLE
Improve the readme

### PR DESCRIPTION
**Pull request by MisterDA**
Passing by, I improved the markdown a bit, fixed some typos, reflowed the text for when the markdown's not rendered.

### CODE REVIEW

**Review by dra27 — COMMENTED** [review]
Typos and improvements always welcome, thank you! The code blocks certainly look much nicer. I'm a bit meh about the reflowing, but I'll let you have it! 🙂

A few other comments here and there...

**Comment by MisterDA** [comment]
Thanks for the proof-reading, I've applied your suggestions.

**Comment by MisterDA** [comment]
I've noticed that some links were broken or outdated an updated them too.

**Comment by dra27** [comment]
Thanks!

**Pull request merged**
